version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.prod
      target: production
    volumes:
      - ./api:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DEBUG: nodejs-docker-express:*
    env_file:
      - ./.env