version: '3.3'
services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    volumes:
      - ./api:/usr/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    env_file:
      - ./.env
      - ./.env.local
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: farouche
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: farouche
    ports:
      - '5431:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
  redis-server: 
    image: 'redis'
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis-server:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis-server
  react-ui:
    build:
      context: ./client
    ports:
      - "2000:2000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - ./client:/usr/src/app/client
volumes:
  redis-data: