version: '3.3'
services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    volumes:
      - ./api:/usr/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    env_file:
      - ./.env
      - ./.env.local