version: '3.3'
services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    volumes:
      - ./api:/usr/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    env_file:
      - ./.env
      - ./.env.local
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: farouche
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: farouche
    ports:
      - '5431:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data