FROM node:18-alpine as build
WORKDIR /usr/app

COPY package.json ./
COPY tsconfig.json ./

COPY src ./src

RUN npm install
RUN npm run build

## this is stage two , where the app actually runs
FROM node:18-alpine
WORKDIR /usr/app

COPY package.json ./

RUN npm install --only=production

COPY --from=build /usr/app/dist .
RUN cat /usr/app/app.js

RUN npm install pm2 -g

EXPOSE 3000

CMD ["pm2-runtime","app.js"]