FROM node:18-alpine as dev

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./
EXPOSE 3000
ENV NODE_ENV=development
RUN npm install -g nodemon
RUN npm install
COPY . .
RUN ls node_modules/@types
CMD ["npm", "run", "start:dev"]