FROM node:18-alpine as production

WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig.json ./

EXPOSE 3000
ENV NODE_ENV=production
RUN npm install typescript -g
RUN npm ci

COPY . .

RUN tsc

COPY . .
CMD ["node", "./dist/src/server.js"]
